FROM ubuntu as dcpp

ENV DEBIAN_FRONTEND "noninteractive"

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	build-essential make cmake

WORKDIR /opt/build

COPY CMakeLists.txt main.cpp /opt/build/

RUN mkdir build;cd build; cmake -S ../ -B .; make

CMD ["build/hello"]
